version: '3'
services:
  nginx:
    image: "nginx:latest"
    container_name: "main_nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error.log"
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "8000:80"
      - "8443:443"

  airports:
    image: "jyotibhanot30/airports-assembly:1.0.1"
    container_name: airports
#    ports:
#      - "81:8080"

  countries:
    image: "jyotibhanot30/countries-assembly:1.0.1"
    container_name: countries
#    ports:
#      - "82:8080"
